### ISSUE TITLE
when onCreate NPE 

### ISSUE THREAD

**Issue by Axrorxoja** [skimarxall/AnchorSheetBehavior#6] opened 2018-07-13 13:40 UTC
`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.ViewDragHelper.processTouchEvent(android.view.MotionEvent)' on a null object reference
        at com.hardsoftstudio.widget.AnchorSheetBehavior.onTouchEvent(AnchorSheetBehavior.java:354)
        at android.support.design.widget.CoordinatorLayout.resetTouchBehaviors(CoordinatorLayout.java:396)
        at android.support.design.widget.CoordinatorLayout.onAttachedToWindow(CoordinatorLayout.java:238)
        at android.view.View.dispatchAttachedToWindow(View.java:18623)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3520)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3527)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3527)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3527)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3527)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3527)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3527)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2040)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1748)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7785)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)`

**Comment by powext** [comment] 2018-08-30 12:26
Same problem here 😢

**Comment by Vahn84** [comment] 2018-09-18 13:46
The problem is that the "onTouchEvent" gets called before the "onLayout" (where the mViewDragHelper is created)

You just have to check for a null eventuality inside the onTouchEvent, and return false if true.


    @Override
    public boolean onTouchEvent(CoordinatorLayout parent, V child, MotionEvent event) {
        Log.e("ANCHOR SHEET", "ON TOUCH");
        if (!child.isShown()) {
            return false;
        }
        int action = event.getActionMasked();
        if (mState == STATE_DRAGGING && action == MotionEvent.ACTION_DOWN) {
            return true;
        }

        if(mViewDragHelper != null) {
            mViewDragHelper.processTouchEvent(event);
        } else {
            return false;
        }
        // Record the velocity
        if (action == MotionEvent.ACTION_DOWN) {
            reset();
        }
        if (mVelocityTracker == null) {
            mVelocityTracker = VelocityTracker.obtain();
        }
        mVelocityTracker.addMovement(event);
        // The ViewDragHelper tries to capture only the top-most View. We have to explicitly tell it
        // to capture the bottom sheet in case it is not captured and the touch slop is passed.
        if (action == MotionEvent.ACTION_MOVE && !mIgnoreEvents) {
            if (Math.abs(mInitialY - event.getY()) > mViewDragHelper.getTouchSlop()) {
                mViewDragHelper.captureChildView(child, event.getPointerId(event.getActionIndex()));
            }
        }
        return !mIgnoreEvents;
    }

**Comment by marcelpinto** [comment] 2018-10-06 11:00
Just pushed a fix sorry for the delay

**Closed as completed by marcelpinto** 2018-10-06 11:00 UTC
